//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsoleApp.A1WCFNameSpace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="A1WCFNameSpace.IA1WCF")]
    public interface IA1WCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IA1WCF/VerifyPrimeNumber", ReplyAction="http://tempuri.org/IA1WCF/VerifyPrimeNumberResponse")]
        string VerifyPrimeNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IA1WCF/VerifyPrimeNumber", ReplyAction="http://tempuri.org/IA1WCF/VerifyPrimeNumberResponse")]
        System.Threading.Tasks.Task<string> VerifyPrimeNumberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IA1WCFChannel : WCFConsoleApp.A1WCFNameSpace.IA1WCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class A1WCFClient : System.ServiceModel.ClientBase<WCFConsoleApp.A1WCFNameSpace.IA1WCF>, WCFConsoleApp.A1WCFNameSpace.IA1WCF {
        
        public A1WCFClient() {
        }
        
        public A1WCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public A1WCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public A1WCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public A1WCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VerifyPrimeNumber() {
            return base.Channel.VerifyPrimeNumber();
        }
        
        public System.Threading.Tasks.Task<string> VerifyPrimeNumberAsync() {
            return base.Channel.VerifyPrimeNumberAsync();
        }
    }
}
